language: php

services:
  - docker

php:
  - 7.0
  - 7.1

before_install:
  - make redis_up
  - composer self-update
  - composer install

script:
  - make test_ci

before_deploy:
  - sudo add-apt-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible
  - openssl aes-256-cbc -K $encrypted_cedc0874a860_key -iv $encrypted_cedc0874a860_iv -in infrastructure/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script:
    - make deploy