services:
    simple_prepaid_card.app_bundle.twig.money_filter:
        class: SimplePrepaidCard\Bundle\AppBundle\Twig\MoneyFilter
        public: false
        arguments:
            - "@simple_prepaid_card.money_decimal_formatter"
        tags:
            - { name: twig.extension }

    simple_prepaid_card.money_decimal_formatter:
        class: SimplePrepaidCard\Common\Model\MoneyDecimalFormatter
        factory: [SimplePrepaidCard\Common\Model\MoneyDecimalFormatter, create]