imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    locale: en

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        creditCard: "@simple_prepaid_card.credit_card.query.credit_card"
        merchant:   "@simple_prepaid_card.coffee_shop.query.merchant"

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%database_path%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            common:
                type: yml
                dir: "%kernel.root_dir%/../src/SimplePrepaidCard/Common/Infrastructure/doctrine"
                prefix: Money
                is_bundle: false
            credit_card:
                type: annotation
                dir: "%kernel.root_dir%/../src/SimplePrepaidCard/CreditCard/Model"
                prefix: SimplePrepaidCard\CreditCard\Model
                is_bundle: false
            coffe_shop:
                type: annotation
                dir: "%kernel.root_dir%/../src/SimplePrepaidCard/CoffeeShop/Model"
                prefix: SimplePrepaidCard\CoffeeShop\Model
                is_bundle: false
            statement:
                type: annotation
                dir: "%kernel.root_dir%/../src/SimplePrepaidCard/CreditCard/Application/Query"
                prefix: SimplePrepaidCard\CreditCard\Application\Query
                is_bundle: false
