security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_MERCHANT: ROLE_USER
        ROLE_HOLDER: ROLE_USER
        ROLE_CUSTOMER: ROLE_HOLDER

    providers:
        in_memory:
            memory:
                users:
                    merchant:
                        password: merchant
                        roles: 'ROLE_MERCHANT'
                    customer:
                        password: customer
                        roles: 'ROLE_CUSTOMER'

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: in_memory
                login_path: login
                check_path: login_check
            logout:       true
            anonymous:    true
            switch_user:  true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }