services:
    simple_prepaid_card.coffee_shop.command_handler.buy_product:
        class: SimplePrepaidCard\CoffeeShop\Application\Command\BuyProductHandler
        arguments:
            - "@simple_prepaid_card.coffee_shop.repository.customer"
            - "@simple_prepaid_card.coffee_shop.products"
            - "@simple_prepaid_card.coffee_shop.credit_card_provider"
        tags:
            - { name: command_handler, handles: SimplePrepaidCard\CoffeeShop\Application\Command\BuyProduct }

    simple_prepaid_card.coffee_shop.command_handler.authorize_merchant:
        class: SimplePrepaidCard\CoffeeShop\Application\Command\AuthorizeMerchantHandler
        arguments:
            - "@simple_prepaid_card.coffee_shop.repository.merchant"
        tags:
            - { name: command_handler, handles: SimplePrepaidCard\CoffeeShop\Application\Command\AuthorizeMerchant }

    simple_prepaid_card.coffee_shop.command_handler.capture_authorization:
        class: SimplePrepaidCard\CoffeeShop\Application\Command\CaptureAuthorizationHandler
        arguments:
            - "@simple_prepaid_card.coffee_shop.repository.merchant"
            - "@simple_prepaid_card.coffee_shop.credit_card_provider"
        tags:
            - { name: command_handler, handles: SimplePrepaidCard\CoffeeShop\Application\Command\CaptureAuthorization }