services:
    simple_prepaid_card.credit_card.query.statement: "@simple_prepaid_card.credit_card.query.statement.doctrine_orm"

    simple_prepaid_card.credit_card.query.statement.doctrine_orm:
        class: SimplePrepaidCard\CreditCard\Infrastructure\DoctrineORMStatementQuery
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - "@simple_prepaid_card.credit_card.query.credit_card_id_of_holder"

    simple_prepaid_card.credit_card.query.credit_card_id_of_holder: "@simple_prepaid_card.credit_card.query.credit_card_id_of_holder.doctrine_orm"

    simple_prepaid_card.credit_card.query.credit_card_id_of_holder.doctrine_orm:
        class: SimplePrepaidCard\CreditCard\Infrastructure\DoctrineORMCreditCardIdOfHolderQuery
        arguments:
            - '@doctrine.orm.default_entity_manager'

    simple_prepaid_card.credit_card.query.credit_card: "@simple_prepaid_card.credit_card.query.credit_card.doctrine_orm"

    simple_prepaid_card.credit_card.query.credit_card.doctrine_orm:
        class: SimplePrepaidCard\CreditCard\Infrastructure\DoctrineORMCreditCardQuery
        arguments:
            - '@doctrine.orm.default_entity_manager'

    simple_prepaid_card.credit_card.projector.statement.doctrine_orm:
        class: SimplePrepaidCard\CreditCard\Infrastructure\DoctrineORMStatementProjector
        arguments:
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: event_subscriber, subscribes_to: SimplePrepaidCard\CreditCard\Model\FundsWereCharged, method: applyThatFundsWereCharged }
            - { name: event_subscriber, subscribes_to: SimplePrepaidCard\CreditCard\Model\FundsWereLoaded, method: applyThatFundsWereLoaded }
