services:
    simple_prepaid_card.credit_card.repository.credit_card: "@simple_prepaid_card.credit_card.repository.credit_card.doctrine_orm"

    simple_prepaid_card.credit_card.repository.credit_card.doctrine_orm:
        class: SimplePrepaidCard\CreditCard\Infrastructure\DoctrineORMCreditCardRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [SimplePrepaidCard\CreditCard\Model\CreditCard]