---
  - name: Prepare cache directory
    file:
      path: "{{ release_dir }}/var/cache"
      state: directory
      mode: 0777
      recurse: true

  - name: Prepare logs directory
    file:
      path: "{{ release_dir }}/var/logs"
      state: directory
      mode: 0777
      recurse: true

  - name: Prepare sessions directory
    file:
      path: "{{ release_dir }}/var/sessions"
      state: directory
      mode: 0777
      recurse: true

  - name: Prepare db directory
    file:
      path: "{{ release_dir }}/var/db"
      state: directory
      mode: 0777
      recurse: true